version: '2'
services:
  es01:
    image: elasticsearch:5.6-alpine
    container_name: es-single
    environment:
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - "discovery.type=single-node"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
       - ./data/es-5.6:/usr/share/elasticsearch/data
       - ./elasticsearch5.6.yml:/usr/share/elasticsearch/config/elasticsearch.yml
    expose:
       - 9200
    ports:
      - 9200:9200
    networks:
      - esnet
  kibana:
    container_name: kibana
    image: kibana:5.6
    ports: 
      - 5601:5601
    links: 
      - es01
    volumes:
      - ./kibana.yml:/usr/share/kibana/config/kibana.yml
    environment:
       SERVER_NAME: kibana.xytschool.com
       ELASTICSEARCH_HOSTS: http://es-single:9200
    networks:
       - esnet
 
         #  filebeat:
         #    container_name: filebeat1
         #    image: docker.elastic.co/beats/filebeat:7.3.2
         #    links: 
         #      - es01
         #    volumes:
         #      - ./filebeat/data:/usr/share/filebeat/data
         #      - ./filebeat/log:/usr/share/filebeat/log
         #      - ./filebeat/filebeat.yml:/usr/share/filebeat/filebeat.yml
         #      - ./filebeat/modules.d:/usr/share/filebeat/modules.d
         #      - /home/gw/code/go/src/github.com/gw123/GMQ/logs:/logs/GMQ
         #      - /home/gw/code/go/src/github.com/fpay/group-order-message-go/logs:/logs/bot
         #      - /home/gw/code/go/bin/pos/logs:/logs/pos
         #      - /home/gw/code/web/laravelschool/storage/logs:/logs/xytschool
         #      - /var/logs/ningx/school:/logs/nginx/access
         #    networks:
         #      - esnet
volumes:
  es-single:
    driver: local

networks:
  esnet:
