version: '2'
services:
  es01:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.3.2
    container_name: es7
    environment:
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - "discovery.type=single-node"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    expose:
       - 9200
    ports:
      - 9207:9200
    networks:
      - esnet
  kibana:
    container_name: kibana7
    image: docker.elastic.co/kibana/kibana:7.3.2
    ports: 
      - 5607:5601
    links: 
      - es01
    environment:
       SERVER_NAME: kibana.xytschool.com
       ELASTICSEARCH_HOSTS: http://es7:9200
    networks:
       - esnet
networks:
  esnet:
